### PR TITLE
Support for older versions of Gtk and Webkit

### LINKED ISSUE #38: Activity not launching/working in sugar-build.
Using sugar-build (latest one! :P) I get

```
Traceback (most recent call last):
  File "/home/broot/sugar-build/build/out/install/bin/sugar-activity", line 220, in <module>
    main()
  File "/home/broot/sugar-build/build/out/install/bin/sugar-activity", line 164, in main
    module = __import__(module_name)
  File "/home/broot/sugar-build/build/out/install/share/sugar/activities/Browse.activity/webactivity.py", line 53, in <module>
    from widgets import TitledTray
  File "/home/broot/sugar-build/build/out/install/share/sugar/activities/Browse.activity/widgets.py", line 109, in <module>
    css_provider.load_from_data(css)
gi._glib.GError: <data>:7:14'min-height' is not a valid property name
Exited with status 1, pid 29998 data (<open file '<fdopen>', mode 'w' at 0xab81de0>, '8d463c472337246bd4f6134416a1aee8a667ea88')
```

Maybe it works on fedora rawhide, or smh. But we should provide support to sugar-build on debian or similars.

### PR DESCRIPTION
**Pull request by cristian99garcia**
Fixes #38 
GCI task: https://codein.withgoogle.com/dashboard/task-instances/6099167363465216/

### CODE REVIEW

**Comment by i5o** [comment]
@samdroid-apps can you give me write access?

**Comment by samdroid-apps** [comment]
Ok

**Comment by quozl** [comment]
Was this committed with `--author`?

**Comment by i5o** [comment]
@quozl on it

**Comment by quozl** [comment]
:grin:

**Comment by i5o** [comment]
Merged.

**Pull request closed without merging**
