### PR TITLE
Create readme.md

### PR DESCRIPTION
**Pull request by Rohith-coder**

### CODE REVIEW

**Comment by Hrishi1999** [comment]
You have used html instead of the markdown. Please follow this https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by Hrishi1999** [comment]
Please explain briefly what is Browse., what does it do. Also, mind the typos. You haven't started sentences with capital letters at many places. Please remove the last paragraph also.

**Comment by quozl** [comment]
@tony37 wrote a valuable response but it did not reach this pull request yet, so I'll copy and paste:
> I don't see any value in this readme. It seems content-free.
>
> The Browse.activity is a Sugar activity. It is not useful to run it outside of
> Sugar. Sugar activities are in general written in Python so mentioning this is
> needed when the activity includes object files.
> 
> However, it is important to know which version of Browse since it has changed
> browsers frequently. Which version of webkit is supported by the version now in
> github. Which versions of Sugar can support it (e.g. 13.2.8/0.110? Current
> Sugar is based on Fedora 18. Which version(s) of Fedora are compatible with the
> Browse activity in github?
>
> Does the version of webkit in this Browse activity compatible with both Intel
> architecture and Arm architecture?
>
> These is the information that should be in the readme.

**Comment by quozl** [comment]
Review; NAK; the text exhibits haste and misunderstanding of the source code, it doesn't look like the author knows what the source code is for, and demonstrates a lack of research or testing of the source code.  I don't think it is worthwhile going into a point by point list of factual errors or irrelevancies; that would be even more negative.  Just have a big think about it and start again.  Hope we can help.

A repository `README.md` has no defined content, but the main audience is _developers_.  You have to know what a developer of Browse needs in order to write it.  Also an audience are _users_ and _integrators_, for which they need compatible versions and lists of dependencies.

Repository description is "An activity to browse the internet; WebKit2 on GTK+ on Sugar Toolkit."  That's a very concise description, and is sufficient.

Sections could be how to use (install Sugar desktop, it will be included automatically, then refer user to https://help.sugarlabs.org), how to integrate (include the list of dependencies), and how to develop (layout of source files, which source files are critical, references to dependency API documentation such as https://developer.sugarlabs.org/sugar3).

Other factual information may include;
- [ ] that the _master_ branch targets an environment with Sugar 0.112 and dependencies on latest Fedora and Debian distributions,
- [ ] that the _not-webkit2_ branch targets Sugar 0.112 on the Fedora 18 and similar environments that don't have well-functioning WebKit2 API.

@tony37, yes, WebKit is supported by them on Intel and ARM architectures, but what WebKit supports is not our problem in this repository.  That's a matter for the WebKit project.

**Comment by quozl** [comment]
Confusing duplicate of https://github.com/sugarlabs/browse-activity/pull/64, closing both, please reflect on the comments there and open a new pull request when you rewrite.

**Comment by quozl** [comment]
Thanks for your contributions, they have been merged with others into commit 978e5a0e6078bc0e03d2db75d9f9513769dfe339.

**Pull request closed without merging**
