### PR TITLE
Fix function call 

### PR DESCRIPTION
**Pull request by Aniket21mathur**

### CODE REVIEW

**Comment by Aniket21mathur** [comment]
@quozl , @pro-panda might have missed it as it does not create any hindrance to testing.

**Comment by pro-panda** [comment]
Thanks, reviewed

**Comment by pro-panda** [comment]
Thanks, you fixed it before me typing the review ;-)

**Comment by Aniket21mathur** [comment]
> Thanks, you fixed it before me typing the review ;-)

Rebase it with master branch :smile: ?

**Comment by Aniket21mathur** [comment]
Thanks for reviewing!

**Pull request merged**
