### PR TITLE
customised search bar

### PR DESCRIPTION
**Pull request by kushagra98**
Added customizations to the search bar as per the #87 
Screenshot from 2019-04-19 19-42-34

### CODE REVIEW

**Comment by samswag** [comment]
Why is the search bar green?

**Comment by kushagra98** [comment]
It's just a colour, there is no reason for it to be green. It can be red, yellow, purple as well!!!

**Comment by kushagra98** [comment]
Someone please check these changes and merge it.
These changes are according to #87

**Comment by quozl** [comment]
I don't think it should be green.  Why have you chosen green?  I don't understand previous answer.

**Comment by kushagra98** [comment]
By the last answer I mean that it can be of any colour. Want me to do it transparent or some else colour?

**Comment by quozl** [comment]
https://github.com/sugarlabs/browse-activity/issues/87 does not specify a colour.  There is a mock-up, with no colour for the text entry field.  Ask in the issue if you have doubts as to what is wanted by @perriefidelis.

**Comment by pro-panda** [comment]
Stale, closing

**Pull request closed without merging**
