### PR TITLE
Allow users to configure search properties

### PR DESCRIPTION
**Pull request by rcunning01**
This pull request will allow users to configure the search engine that they use with the Browse activity. This is a continuation of #93 with new code.

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Good start.  We also need a way for the average user to choose a search engine.

Perhaps this is related to my previous questions which you've not yet answered; why does the file need to be reached through the XDG_DATA_DIRS environment variable?

What happens when a user upgrades from Browse-203.1 to the next release we make?  At the least, there will be files left in `data/schemas`.

Wouldn't it be better not to change the path?

**Comment by rcunning01** [comment]
The manual page for `glib-compile-schemas(1)` states that "[a]t runtime, GSettings looks for schemas in the `glib-2.0/schemas` subdirectories of all directories specified in the `XDG_DATA_DIRS` environment variable. The usual location to install schema files is `/usr/share/glib-2.0/schemas`."

I will also upload new code to this pull request to enable Browse to (temporarily) delete the entire `data/schemas` directory and all its contents if it is present. (I expect this code to be removed in the near future.)

**Comment by quozl** [comment]
Thanks, but as I said before, our use of _Gio.SettingsSchemaSource.new_from_directory_ in `browser.py` means `XDG_DATA_DIRS` is not used by Browse activity to locate the schema source.

* [PyGObject API Reference for _Gio.SettingsSchemaSource.new_from_directory_](https://lazka.github.io/pgi-docs/Gio-2.0/classes/SettingsSchemaSource.html#Gio.SettingsSchemaSource.new_from_directory),
* [Where `browser.py` calls _Gio.SettingsSchemaSource.new_from_directory_](https://github.com/sugarlabs/browse-activity/blob/master/browser.py#L128)

So there is no need to change the directory.

We also need a way for the average user to choose a search engine.

**Comment by rcunning01** [comment]
One way to do that would be for Browse to display a drop-down menu showing a list of configured search engines and having an option to add a new one. But I do not know enough PyGObject to program such a thing.

  -----Original Message-----

**Comment by quozl** [comment]
Okay, thanks.  Let's see if anyone else wants to take the job.  @nswarup14, you may be interested.

**Comment by rcunning01** [comment]
Of course, users can also directly change the value of the `url_search` constant in `browser.py` to one of their liking, such as `http://yandex.com/search/?text=%(query)s`, `http://bing.com/search?q=%(query)s`, `http://search.yahoo.com/search?q=%(query)s`, `https://en.wikipedia.org/w/index.php?title=Special%%3ASearch&search=%(query)s`, or `https://www.youtube.com/results?search_query=%(query)s`. But (at least in Sugar on a Stick) this will revert back to the default value when users update their copies of the Browse activity.

**Comment by quozl** [comment]
Not our users.  Also, you haven't changed `data/index.html` to support alternate search engines?  Our users typically search from the default page, not from the URL entry box.

**Comment by rcunning01** [comment]
Closing #94. (I am closing this again because this is the only way to avoid conflicts with the base branch when I am using GitHub's Web interface.) Again, I will open a new pull request shortly.

**Comment by quozl** [comment]
I guess GitHub's web interface isn't any good for this sort of thing yet.  I recommend learning how to use git on your own computer, it is way more powerful than GitHub is.  And it is fun.

**Pull request closed without merging**
