### PR TITLE
Incorporated Ctrl+C and Ctrl+V for url toolbar hence fixes #4642

### PR DESCRIPTION
**Pull request by gauravm043**

### CODE REVIEW

**Comment by SAMdroid-apps** [comment]
Are you 100% sure that you want to re-implement a native function?

Is there no other way to fix this?

**Comment by davelab6** [comment]
thanks @gauravm043 !! :) 

@samdroid-apps do you want to close this as unacceptable?

**Comment by i5o** [comment]
We should close this, or mark as needs-work

I don't have the rights in this repository to close btw.

**Comment by quozl** [comment]
In Browse-200 the URL entry text can be selected then copied using the right mouse button, however there are no keyboard shortcuts that I can find.  What are they meant to be?  What is the native function?

**Comment by i5o** [comment]
It should be "Ctrl + C" and "Ctrl + V" as usual in every text entry

**Comment by quozl** [comment]
Yes, but it does not work in Browse.

When you press ctrl+c you get a noise and no copy is made.  When you press ctrl+v after, nothing happens.  Also affects the activity name entry in the first toolbar icon.

Does not affect the activity name entry in the Clock activity, so it is probably not a toolkit problem.

Still further, the right-click menu item *paste* does not work in the URL entry.

**Pull request closed without merging**
