### PR TITLE
Make Ctrl+(1-9) changes current tab to that number.

### PR DESCRIPTION
**Pull request by vikramahuja1001**

### CODE REVIEW

**Comment by SAMdroid-apps** [comment]
Are there any other browsers that do this?

**Comment by vikramahuja1001** [comment]
All the browsers do this

**Comment by SAMdroid-apps** [comment]
Mate, Firefox is a browser, and it doesn't do it.

**Comment by vikramahuja1001** [comment]
Even firefox does it. You can see all the firefox shortcuts here http://www.accessfirefox.org/Firefox_Keyboard_and_Mouse_Shortcuts.html

**Comment by SAMdroid-apps** [comment]
Oh, the linux version of that keybinding is `Alt+[1…9]`, not `Ctrl`.

Sorry

**Comment by vikramahuja1001** [comment]
So what do you think?

**Comment by SAMdroid-apps** [comment]
I will test it

**Comment by samdroid-apps** [comment]
Sorry about taking so long to test.

I can't get it to actually work:

```
Traceback (most recent call last):
  File "/home/saam/sugar-build/build/out/install/share/sugar/activities/Browse.activity/webactivity.py", line 558, in _key_press_cb
    self._tabbed_view.set_current_page(int(keyname) - 1)
NameError: global name 'keyname' is not defined
```

Also, please make sure your patch conforms to pep8!

**Comment by vikramahuja1001** [comment]
Will check it again

**Comment by davelab6** [comment]
@vikramahuja1001 wow its been a while! :D I think this is a really great patch, but it is now a bit out of date so needs to be rebased from master. Would you be willing to do this? :)

**Comment by vikramahuja1001** [comment]
@davelab6 , sorry for the late reply. I would love to do it again asap

**Comment by samdroid-apps** [comment]
Actually, I was thinking about this recently, and I read about Gtk+ key themes. [1]  Maybe that is the better way to do it, because it is system wide?

[1]  see "Key Bindings" in https://developer.gnome.org/gtk3/stable/chap-css-overview.html

**Comment by quozl** [comment]
We have lost momentum on this one, so I'll close it rather than make a future promise on the issues list.  If anyone wants this feature, please reopen this pull request or a open a new one.  I was hoping to, but eventually unable to; find a corresponding issue, bug or request for feature.

**Pull request closed without merging**
