### PR TITLE
Fix downloading files

### PR DESCRIPTION
**Pull request by City-busz**
This fixes the type error, which happens when downloading files.

### CODE REVIEW

**Comment by quozl** [comment]
Your change switches from single non-tuple value to a dictionary of values, but no other change to function.  I'm against merging this, because I don't understand it.

What is the type error?  How to reproduce the error?  How does this patch fix it?

**Comment by City-busz** [comment]
Without this change, I always get the following error, when I'm trying to download any files:
```
Traceback (most recent call last):
  File "/usr/share/sugar/activities/Browse.activity/downloadmanager.py", line 204, in __state_change_cb
    % self._source
TypeError: not all arguments converted during string formatting
```
And the download fails, it remains in pending state in journal.

**Comment by quozl** [comment]
Thanks, very interesting.  Sounds like a translation failure.  Please tell me:

* language you have set,
* the format string is after translation by gettext.

**Comment by City-busz** [comment]
> language you have set,

I'm using 'LANG=hu_HU.utf8' as system locale.

> the format string is after translation by gettext.

I don't know how to get this.

**Comment by City-busz** [comment]
Ah, now I see, the problem is in the Hungarian translation:
https://github.com/sugarlabs/browse-activity/blob/master/po/hu.po#L93
It's missing the parameter...

**Comment by quozl** [comment]
Yes, it is missing the parameter, please try editing the po/hu.po and let me know if that fixes it.

Should you need it, a method to get the translated string; edit the downloadmanager.py file at the point of your change, to print the format string after translation;

```
    import sys
    print >>sys.stderr, _('From: %s')
```

Then run the activity, reproduce the problem, and then read the activity log file.

**Comment by City-busz** [comment]
Yes, it fixes the problem. Thanks for pointing out the real bug.

I created another PR: https://github.com/sugarlabs/browse-activity/pull/29

**Pull request closed without merging**
